spring:
  datasource:
    url: jdbc:h2:mem:memorydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # Desative o show-sql para evitar logs SQL no console
  sql:
    init:
      mode: always # Garante que os scripts de inicialização sejam executados, se houver

logging:
  level:
    org.hibernate.SQL: warn # Reduz os logs de SQL do Hibernate para WARN
    org.hibernate.type.descriptor.sql.BasicBinder: warn # Reduz os logs de binding de parâmetros para WARN